"use client";
import { FormEvent, useState } from "react";
type RecordResult = { id: string; status: string; statusNote: string; filedOn: string; slaDeadline: string; daysLeft: number; draft: { department: string; location: string } };
const date = (value: string) => new Date(value).toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
export default function TrackPage() {
  const [id, setId] = useState(""); const [result, setResult] = useState<RecordResult | null>(null); const [error, setError] = useState("");
  const lookup = async (event: FormEvent) => { event.preventDefault(); setError(""); setResult(null); const response = await fetch(`/api/track/${encodeURIComponent(id)}`); const data = await response.json(); if (!response.ok) { setError(data.error); return; } setResult(data); };
  const statusHeadline = (record: RecordResult) => record.status === "Disposed" ? "This grievance has been closed." : record.daysLeft === 0 ? "The standard response window has passed." : `There are ${record.daysLeft} days left in the standard response window.`;
  return <section className="page"><div className="track-wrap"><p className="eyebrow">Already have a registration number?</p><h1 className="page-title">See what is happening with your grievance.</h1><p className="subhead">Enter the number you received when your grievance was acknowledged. In this prototype, that is all you need — no password or captcha.</p><form className="track-form" onSubmit={lookup}><input value={id} onChange={event => setId(event.target.value)} placeholder="SAA/2026/DEMO01" aria-label="Registration number"/><button className="button" type="submit">Check status</button></form><p className="demo-hint">Try a demo record: <button type="button" onClick={() => setId("SAA/2026/DEMO01")}>water supply</button> or <button type="button" onClick={() => setId("SAA/2026/DEMO02")}>train refund</button>.</p>{error && <p className="error">{error}</p>}{result && <article className="result" aria-live="polite"><p className="status-chip">{result.status}</p><h2 className="result-status">{statusHeadline(result)}</h2><div className="status-explainer"><p className="eyebrow">What this means</p><p>{result.statusNote}</p></div><dl><dt>Registration number</dt><dd className="mono">{result.id}</dd><dt>Sent to</dt><dd>{result.draft.department}</dd><dt>Filed</dt><dd>{date(result.filedOn)}</dd><dt>Expected response</dt><dd>{result.status === "Disposed" ? "This grievance has been resolved." : `By ${date(result.slaDeadline)}. If it takes longer, the department should send an interim reply explaining the delay.`}</dd></dl></article>}</div></section>;
}
