"use client";
import { FormEvent, useState } from "react";
import { HealthField, GrievanceDraft, ChatTurn } from "@/types/grievance";
import { HealthScoreSeal } from "@/components/HealthScoreSeal";

const blank: GrievanceDraft = { summary: null, fullText: null, location: null, department: null, dateOrTimeframe: null, desiredOutcome: null };
const questionFor = (draft: GrievanceDraft) => !draft.department ? "Which public service is this about? Water, roads, railways, banking, a pension, or something else?" : !draft.location ? "Where did this happen? A locality, city, or nearby landmark is enough." : !draft.desiredOutcome ? "What would a useful resolution look like for you?" : "The key details are in place. Add anything that would help the officer understand the situation, or review the draft.";
function infer(message: string, draft: GrievanceDraft) {
  const lower = message.toLowerCase(); const next = { ...draft };
  const department = lower.match(/water|paani|sewage|drain|tap/) ? "Drinking Water and Sanitation" : lower.match(/pothole|road|rto|licence/) ? "Road Transport and Highways" : lower.match(/train|railway|irctc|ticket/) ? "Railways" : lower.match(/bank|atm|loan|refund/) ? "Financial Services (Banking)" : lower.match(/pension|ppo|retire/) ? "Pensions and Pensioners Welfare" : lower.match(/ration|pds/) ? "Food and Public Distribution" : null;
  if (department) next.department = department;
  if (!next.summary) next.summary = message.trim();
  if (!next.fullText) next.fullText = `I am writing to report the following public-service issue: ${message.trim()}. I request that the matter be examined and resolved, and that I be informed of the action taken.`;
  const place = message.match(/(?:in|at|near|from)\s+([A-Za-z0-9 ,.-]{3,48})/i); if (place && !next.location) next.location = place[1].replace(/\b(for|since|please|and)\b.*$/i, "").trim();
  if (/today|yesterday|days|week|month|since|for \d+/i.test(lower)) next.dateOrTimeframe ||= "Timeframe mentioned in the description";
  if (/please|want|restore|repair|fix|refund|resolve|action|replace/i.test(lower)) next.desiredOutcome ||= "Resolve the issue and share an update";
  return next;
}
function captured(draft: GrievanceDraft): HealthField[] { const fields: HealthField[] = []; if (draft.summary) fields.push("issueDescribed"); if (draft.location) fields.push("location"); if (draft.department) fields.push("department"); if (draft.dateOrTimeframe) fields.push("dateOrTimeframe"); if (draft.desiredOutcome) fields.push("desiredOutcome"); if (draft.fullText && draft.fullText.length > 100) fields.push("supportingDetail"); return fields; }
export default function FilePage() {
  const [history, setHistory] = useState<ChatTurn[]>([{ role: "assistant", content: "What has gone wrong? Start with the service, the problem, and any detail you remember. Hindi, English, or a mix is fine." }]);
  const [text, setText] = useState(""); const [draft, setDraft] = useState(blank); const [name, setName] = useState(""); const [registration, setRegistration] = useState<string | null>(null); const health = captured(draft); const ready = Boolean(draft.summary && draft.location && draft.department && draft.desiredOutcome);
  const send = (event: FormEvent) => { event.preventDefault(); if (!text.trim()) return; const updated = infer(text, draft); setDraft(updated); setHistory([...history, { role: "user", content: text }, { role: "assistant", content: questionFor(updated) }]); setText(""); };
  const submit = async () => { const response = await fetch("/api/submit", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ draft, citizenName: name || "Citizen" }) }); const data = await response.json(); setRegistration(data.registrationId); };
  return <section className="file-layout"><div className="chat-panel"><div><p className="eyebrow">Step 1 of 1 · Nothing is sent while you write</p><h1 className="chat-heading">What needs fixing?</h1><p className="chat-intro">Describe the problem as you remember it. We’ll ask for one missing detail at a time.</p></div><div className="messages" aria-live="polite">{history.map((turn, index) => <div className={`bubble ${turn.role}`} key={index}>{turn.content}</div>)}</div><form className="message-form" onSubmit={send}><input value={text} onChange={event => setText(event.target.value)} placeholder="Example: No water supply in Ward 14 since Monday" aria-label="Describe your grievance"/><button className="button" type="submit">Continue</button></form></div><aside className="draft-panel"><div className="draft-header"><div><p className="eyebrow">Your case file · not sent yet</p><h2 className="draft-title">Check before you submit.</h2></div><HealthScoreSeal captured={health}/></div><dl className="draft-fields">{[["Public service", draft.department], ["Where it happened", draft.location], ["When it started", draft.dateOrTimeframe], ["What you need", draft.desiredOutcome], ["Draft grievance", draft.fullText]].map(([label, value]) => <div className="draft-field" key={label as string}><dt>{label}</dt><dd className={value ? "" : "empty"}>{value || "We’ll fill this in as you talk."}</dd></div>)}</dl>{registration ? <div className="confirmation"><strong>Grievance submitted</strong><p>Save this registration number. You can use it to track updates.</p><p className="mono">{registration}</p><p className="confirmation-note">This is a demo record created by the prototype, not a submission to the Government of India.</p></div> : <div className="submit-area"><label htmlFor="citizen-name">Your name <span>(for the record)</span></label><input id="citizen-name" className="name-input" value={name} onChange={event => setName(event.target.value)} placeholder="Enter your name"/><button className="button ready" disabled={!ready} onClick={submit}>Submit grievance</button><p className="submit-hint">You can submit when the issue, service, place, and requested resolution are clear.</p></div>}</aside></section>;
}
